name: Publish

on:
  workflow_dispatch: # 手动触发
    inputs:
      version:
        description: '版本号'
        required: true

jobs:

  job1:
    name: Create Release
    runs-on: ubuntu-latest
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }} 
    
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: true
          prerelease: false

  job2:
    name: Build
    needs: job1
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os:
          - win-x86
          - win-x64
          - linux-arm
          - linux-x64
          - osx-x64
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.100

      - name: Build project
        run: |
          cd ./test
          dotnet restore
          dotnet build --configuration Release --no-restore
          cd ./src/Ray.BiliBiliTool.Console
          dotnet publish --self-contained false -o ./bin/Publish/net5-dependent
          dotnet publish --runtime ${{ matrix.os }} --self-contained true -o ./bin/Publish/${{ matrix.os }}
          cd ./bin/Publish
          zip -q -r  bilibili-tool-v${{ github.event.inputs.version }}-net5-dependent.zip net5-dependent
          zip -q -r  bilibili-tool-v${{ github.event.inputs.version }}-${{ matrix.os }}.zip ${{ matrix.os }}
      
      - name: Upload dependent assets
        id: upload-dependent-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./test/src/Ray.BiliBiliTool.Console/bin/Publish/bilibili-tool-v${{ github.event.inputs.version }}-net5-dependent.zip
          asset_name: bilibili-tool-v${{ github.event.inputs.version }}-net5-dependent.zip
          asset_content_type: application/zip

      - name: Upload assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./test/src/Ray.BiliBiliTool.Console/bin/Publish/bilibili-tool-v${{ github.event.inputs.version }}-${{ matrix.os }}.zip
          asset_name: bilibili-tool-v${{ github.event.inputs.version }}-${{ matrix.os }}.zip
          asset_content_type: application/zip
